import type {
  DownloadItem,
  MentorItem,
  ProjectItem,
  StartupShowcaseItem,
} from "./types";

export const CIEL_METRICS = [
  { label: "Student Council Members", value: "~200", prefix: "" },
  { label: "Startups Registered", value: "10–12", prefix: "" },
  { label: "Industry Partners", value: "3–5", prefix: "" },
  { label: "Possibilities", value: "Infinite", prefix: "∞ " },
];

export const FEATURED_STARTUPS: StartupShowcaseItem[] = [
  {
    id: "st-1",
    name: "Austrange Solutions",
    sector: "Assistive Tech & Accessibility",
    stage: "incubation",
    founder: "CIEL Student Innovators",
    description: "Making life easier for specially enabled individuals through assistive hardware and software solutions.",
    logo: "/logo.png",
    fundingRaised: "Incubated at CIEL",
    website: "#",
  },
  {
    id: "st-2",
    name: "Hydra Edge",
    sector: "Smart IoT & HealthTech",
    stage: "mvp",
    founder: "CIEL Student Innovators",
    description: "Smart IoT AI brand that uses AI and IoT to monitor body signals and predict hydration in real time.",
    logo: "/logo.png",
    fundingRaised: "Incubated at CIEL",
    website: "#",
  },
  {
    id: "st-3",
    name: "Synko",
    sector: "FinTech & Smart Commerce",
    stage: "incubation",
    founder: "CIEL Student Innovators",
    description: "Smart Shopping Companion that helps consumers save money through intelligent deal and pricing analysis.",
    logo: "/logo.png",
    fundingRaised: "Incubated at CIEL",
    website: "#",
  },
  {
    id: "st-4",
    name: "Pravaah",
    sector: "FashionTech & Generative AI",
    stage: "incubation",
    founder: "CIEL Student Innovators",
    description: "AI-powered fashion innovation platform that offers designers and brands tools for AI-driven creative workflows.",
    logo: "/logo.png",
    fundingRaised: "Incubated at CIEL",
    website: "#",
  },
  {
    id: "st-5",
    name: "Athena",
    sector: "3D Visualization & AR",
    stage: "incubation",
    founder: "CIEL Student Innovators",
    description: "AI-powered 3D visualization software that transforms 2D scans into 3D augmented reality models.",
    logo: "/logo.png",
    fundingRaised: "Incubated at CIEL",
    website: "#",
  },
  {
    id: "st-6",
    name: "Nexora",
    sector: "AI & Lifestyle Tech",
    stage: "mvp",
    founder: "CIEL Student Innovators",
    description: "AI wardrobe assistant providing personalized outfit recommendations, styling, and wardrobe intelligence.",
    logo: "/logo.png",
    fundingRaised: "Incubated at CIEL",
    website: "#",
  },
  {
    id: "st-7",
    name: "LogiApp",
    sector: "Logistics & Supply Chain",
    stage: "incubation",
    founder: "CIEL Student Innovators",
    description: "Real-time route optimization and fleet dispatch intelligence platform tailored for logistics firms.",
    logo: "/logo.png",
    fundingRaised: "Incubated at CIEL",
    website: "#",
  },
  {
    id: "st-8",
    name: "SatSecure",
    sector: "AutoTech & IoT Safety",
    stage: "incubation",
    founder: "CIEL Student Innovators",
    description: "IoT-based car safety solution that actively detects road hazards and enhances driver protection.",
    logo: "/logo.png",
    fundingRaised: "Incubated at CIEL",
    website: "#",
  },
  {
    id: "st-9",
    name: "Liminox",
    sector: "CleanTech & Water IoT",
    stage: "incubation",
    founder: "CIEL Student Innovators",
    description: "Smart water quality monitoring system providing real-time telemetry analysis for safe water access.",
    logo: "/logo.png",
    fundingRaised: "Incubated at CIEL",
    website: "#",
  },
  {
    id: "st-10",
    name: "Handvoice",
    sector: "Assistive AI & Computer Vision",
    stage: "mvp",
    founder: "CIEL Student Innovators",
    description: "An AI-based sign language translator enabling seamless two-way communication for deaf and hard-of-hearing communities.",
    logo: "/logo.png",
    fundingRaised: "Incubated at CIEL",
    website: "#",
  },
];

export const ACCELERATOR_STARTUPS: StartupShowcaseItem[] = [
  {
    id: "acc-1",
    name: "24 Organic Mantra",
    sector: "Organic Foods & Sustainable D2C",
    stage: "scale",
    founder: "CIEL Accelerated Venture",
    description: "Certified organic agricultural produce, chemical-free staples, and farm-to-table sustainable nutrition brand.",
    logo: "/logo.png",
    fundingRaised: "Accelerated at CIEL",
    website: "#",
  },
  {
    id: "acc-2",
    name: "DryGrab",
    sector: "Consumer Products & Moisture Care",
    stage: "market",
    founder: "CIEL Accelerated Venture",
    description: "Innovative moisture-absorbing and rapid-drying solutions designed for consumer, household, and retail care.",
    logo: "/logo.png",
    fundingRaised: "Accelerated at CIEL",
    website: "#",
  },
  {
    id: "acc-3",
    name: "GD",
    sector: "Brand Strategy & Digital Solutions",
    stage: "scale",
    founder: "CIEL Accelerated Venture",
    description: "Full-stack digital acceleration, creative design architecture, and enterprise digital growth consultancy.",
    logo: "/logo.png",
    fundingRaised: "Accelerated at CIEL",
    website: "#",
  },
  {
    id: "acc-4",
    name: "Summit Roof Cleaning",
    sector: "Specialized Services & Facility Care",
    stage: "market",
    founder: "CIEL Accelerated Venture",
    description: "Professional eco-friendly roof restoration, commercial property maintenance, and specialized cleaning services.",
    logo: "/logo.png",
    fundingRaised: "Accelerated at CIEL",
    website: "#",
  },
  {
    id: "acc-5",
    name: "Byte Elephants",
    sector: "Enterprise Software & Cloud Tech",
    stage: "scale",
    founder: "CIEL Accelerated Venture",
    description: "Scalable software engineering, custom cloud architecture, and modern product development for growing enterprises.",
    logo: "/logo.png",
    fundingRaised: "Accelerated at CIEL",
    website: "#",
  },
  {
    id: "acc-6",
    name: "Lets Balance Kitchen",
    sector: "Healthy Culinary & Cloud Kitchen",
    stage: "scale",
    founder: "CIEL Accelerated Venture",
    description: "Nutritious balanced meal plans, calorie-conscious culinary recipes, and subscription-based healthy food deliveries.",
    logo: "/logo.png",
    fundingRaised: "Accelerated at CIEL",
    website: "#",
  },
];

export const CIEL_MENTORS: MentorItem[] = [
  {
    id: "m-1",
    name: "Dr. Rajesh Kulkarni",
    designation: "Chief Innovation Advisor",
    organization: "Ex-Director, Tech Ventures",
    expertise: ["Venture Capital", "IP Strategy", "DeepTech"],
    avatar: "RK",
    category: "industry",
  },
  {
    id: "m-2",
    name: "Sunita Nambiar",
    designation: "Managing Partner",
    organization: "Vanguard Seed Fund",
    expertise: ["Early Stage Angel Funding", "Go-To-Market", "SaaS Scale"],
    avatar: "SN",
    category: "investor",
  },
  {
    id: "m-3",
    name: "Prof. Arvind Mehta",
    designation: "Head of Research & IPR",
    organization: "Chetana Institute",
    expertise: ["Patent Drafting", "Tech Transfer", "Material Sciences"],
    avatar: "AM",
    category: "academic",
  },
  {
    id: "m-4",
    name: "Priya Nair",
    designation: "Founder & CEO",
    organization: "GreenGrid Energy (CIEL Alumnus)",
    expertise: ["CleanTech", "Hardware Prototyping", "Supply Chain"],
    avatar: "PN",
    category: "alumni",
  },
];

export const CIEL_DOWNLOADS: DownloadItem[] = [
  {
    id: "d-1",
    title: "CIEL Incubation & Seed Support Policy Handbook",
    category: "policy",
    fileSize: "2.4 MB",
    format: "PDF",
    updatedAt: "2026-01-15",
    description: "Official guidelines covering equity terms, seed grant disbursal, lab usage, and IP sharing ratio.",
  },
  {
    id: "d-2",
    title: "Institutional Intellectual Property (IPR) Policy",
    category: "policy",
    fileSize: "1.8 MB",
    format: "PDF",
    updatedAt: "2025-11-20",
    description: "Comprehensive policy regarding student/faculty patent ownership, commercialization, and royalties.",
  },
  {
    id: "d-3",
    title: "Incubation Application & Pitch Deck Template",
    category: "template",
    fileSize: "5.1 MB",
    format: "ZIP",
    updatedAt: "2026-02-01",
    description: "Standard slide structure, financial projection sheet, and executive summary format required for evaluation.",
  },
  {
    id: "d-4",
    title: "Student Innovation Council Charter & Constitution",
    category: "manual",
    fileSize: "1.2 MB",
    format: "PDF",
    updatedAt: "2025-09-10",
    description: "Operational framework, roles, selection criteria, and event hosting guidelines for student leaders.",
  },
  {
    id: "d-5",
    title: "Annual Incubation & Impact Report 2025-26",
    category: "report",
    fileSize: "8.6 MB",
    format: "PDF",
    updatedAt: "2026-01-05",
    description: "Performance metrics, graduate startups, grant allocations, patent filings, and industry partnerships.",
  },
];

export const GOVERNANCE_COMMITTEES = [
  {
    id: "governing-committee",
    name: "Governing Committee",
    description: "Apex institutional decision-making body establishing strategic governance policies, resource allocations, and venture acceleration mandates for CIEL.",
    members: [
      { name: "Dr. B. R. Patil", role: "Chairman, Governing Board" },
      { name: "Prof. S. R. Joshi", role: "Director, Chetana Institute" },
      { name: "Dr. Rajesh Kulkarni", role: "CEO, CIEL Innovation Hub" },
      { name: "Mr. Anand Rathi", role: "Industry Representative (Managing Director, Rathi Tech)" },
    ],
  },
  {
    id: "joint-steering-committee",
    name: "Joint-Steering Committee",
    description: "Provides operational leadership, interdisciplinary academic integration, cross-faculty research synergy, and ecosystem partner alignment.",
    members: [
      { name: "Prof. Arvind Mehta", role: "Chair, Joint-Steering & Research" },
      { name: "Dr. Smita Rao", role: "Director of Academic Partnerships" },
      { name: "Sunita Nambiar", role: "Venture Partner, Lead Investor" },
      { name: "Karan Johar", role: "Senior Partner, Angel Network" },
    ],
  },
  {
    id: "functional-committee",
    name: "Functional Committee",
    description: "Operational leadership bodies executing CIEL's 6 core innovation tracks, each spearheaded by a dedicated committee lead.",
    members: [
      { name: "Dr. Arvind Mehta", role: "Lead — 1. Innovation and Research" },
      { name: "Dr. Rajesh Kulkarni", role: "Lead — 2. Incubation and Start-up Support" },
      { name: "Prof. Smita Rao", role: "Lead — 3. Skill Development and Training" },
      { name: "Mr. Anand Rathi", role: "Lead — 4. Industry and Investor" },
      { name: "Ms. Meera Fernandez", role: "Lead — 5. Events and Outreach" },
      { name: "Prof. S. R. Joshi", role: "Lead — 6. Monitoring and Evaluation" },
    ],
  },
];

export const STUDENT_COUNCIL_LEADS = [
  { name: "Aarav Sharma", role: "President, Student Innovation Council", branch: "Computer Engineering", year: "Final Year" },
  { name: "Neha Kadam", role: "Vice President, Hackathons & Competitions", branch: "Information Technology", year: "Final Year" },
  { name: "Rishi Verma", role: "Lead, Prototyping & Makerspace Labs", branch: "Mechanical Engineering", year: "Pre-Final Year" },
  { name: "Ananya Roy", role: "Lead, Women Entrepreneurship Cell", branch: "Electronics & Telecom", year: "Pre-Final Year" },
  { name: "Devansh Mehta", role: "Lead, Industry Outreach & Media", branch: "Management Studies", year: "Final Year" },
];

export const DEFAULT_GOOGLE_FORMS = [
  {
    id: "gf-1",
    title: "CiEL Registration",
    description: "Official registration form for Centre for Innovation & Entrepreneurship Learning (CiEL) incubation program.",
    category: "Incubation",
    formUrl: "https://docs.google.com/forms/d/e/1FAIpQLSe4TiDARd-MAr5xgmzHlu7tf2UnVU6uJ_uU4fx3fdNknzi1mw/viewform?usp=header",
    embedUrl: "https://docs.google.com/forms/d/e/1FAIpQLSe4TiDARd-MAr5xgmzHlu7tf2UnVU6uJ_uU4fx3fdNknzi1mw/viewform?embedded=true",
    isActive: true,
    createdAt: "2026-02-01T10:00:00.000Z",
  },
  {
    id: "gf-2",
    title: "SiC for CiEL",
    description: "Application and membership registration form for the Student Innovation Council (SiC) at CiEL.",
    category: "Student Council",
    formUrl: "https://docs.google.com/forms/d/e/1FAIpQLScCGydXqb45XNLxuc_t1WMmRg0j3rePsmGBjSzZU_1s2R-VNA/viewform",
    embedUrl: "https://docs.google.com/forms/d/e/1FAIpQLScCGydXqb45XNLxuc_t1WMmRg0j3rePsmGBjSzZU_1s2R-VNA/viewform?embedded=true",
    isActive: true,
    createdAt: "2026-02-10T12:30:00.000Z",
  },
];


